version: '3'

services:
    nginx:
        image: nginx
        build: 
          context: ./nginx
        volumes:
          - ./nginx:/etc/nginx
        restart: always
        links:
            - api
            - web
        ports:
            - 3000:443
        command: /bin/bash -c "cp /etc/nginx/nginx.local.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

    api:
        build:
          context: ./api
          dockerfile: Dockerfile
        volumes:
            - ./api:/app
        ports:
            - 3002:3002
        env_file:
            - ./api/.env
        links:
            - database
        command: ['npm', 'start']
        
    web:
        build:
          context: ./web
          dockerfile: Dockerfile
        env_file:
            - ./web/.env
        links:
          - api
        ports:
          - 3001:3001
        volumes:
          - ./web:/app
        command: npm run dev

    database:
        image: postgres:9.6-alpine
        ports:
            - 11543:5432
        volumes:
            - database-data:/var/lib/postgresql/data

volumes:
    database-data: {}
